language: ruby
rvm:
  - "2.0.0-p353"
  - "1.9.2"
  - "1.9.3"
  - jruby-18mode # JRuby in 1.8 mode
  - jruby-19mode # JRuby in 1.9 mode
  - rbx
addons:
  postgresql: "9.3"

script:
  - bundle exec rspec spec

before_script:
  - psql -c 'create database flash_card_mаnаger_test;' -U postgres

