default: &default
  adapter: postgresql
  encoding: utf8
  host: localhost
  username: lelikGR
  password: vnc4369400
  pool: 5
  port: 5432


development:
  <<: *default
  database: flash_card_mаnаger_development

test:
  <<: *default
  database: flash_card_mаnаger_test

production:
  <<: *default
  database: flash_card_mаnаger_production
